
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-operator-configmap-role
  namespace: patch-operator-test-ns
rules:
- apiGroups: [""] 
  resources: ["configmaps", "configmap"] 
  verbs: [ "list", "get", "watch", "patch" ]
